/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent(props) {
  return (
    <>
      <div className="div">
        <div className="div-2">
          <div className="div-3">Sign up for Form Builder </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/47ce4d59489c65ca7b87207a1a33b72dfe4924a96092f2d909fbea0206a313ed?apiKey=0d44358c349241a884bac570e8081cff&"
            className="img"
          />
        </div>
        <div className="div-4">
          Form Builder is free to use. Sign up using your email address or phone
          number below to get started.
        </div>
        <div className="div-5">Email or phone number</div>
        <div className="div-6">mail@mail.com</div>
        <div className="div-7">Password</div>
        <div className="div-8">
          <div className="div-9">6digits</div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a961c3c35fde2fd7d2939fb8c855701cb5c422d3ebdb380f60898a7488a49604?apiKey=0d44358c349241a884bac570e8081cff&"
            className="img-2"
          />
        </div>
        <div className="div-10">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/7ccfe8dd5be863fe810993d166273f806a70cb474854614380b5e754703e0544?apiKey=0d44358c349241a884bac570e8081cff&"
            className="img-3"
          />
          <div className="div-11">
            <span style="color: rgba(184,188,202,1);">I agree to the </span>
            <span style="color: rgba(0,72,217,1);">terms and conditions</span>
          </div>
        </div>
        <div className="div-12">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/8b5c905490ec6c47819f51cd5917de8ee192a5d2501f62216b438e475d6f7dad?apiKey=0d44358c349241a884bac570e8081cff&"
            className="img-4"
          />
          <div className="div-13">Send me the latest deal alerts</div>
        </div>
        <div className="div-14">Create account</div>
        <div className="div-15">
          <div className="div-16" />
          <div className="div-17">or</div>
          <div className="div-18" />
        </div>
        <div className="div-19">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/00c7fa8e197cdf8156c10103993b7acd6bf46eeca5e5cc686b67c7cdeddd5048?apiKey=0d44358c349241a884bac570e8081cff&"
            className="img-5"
          />
          <div className="div-20">Continue with Google</div>
        </div>
        <div className="div-21">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/aff859ad7c162b2ee1358b5c227e7284ece444b6950ddaa45f94876cc62983ae?apiKey=0d44358c349241a884bac570e8081cff&"
            className="img-6"
          />
          <div className="div-22">Continue with Apple</div>
        </div>
        <div className="div-23">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/7ea49d70e0e05d8fbd75028824b5b464ce895fae81c02ff49fb9fa2a188a3883?apiKey=0d44358c349241a884bac570e8081cff&"
            className="img-7"
          />
          <div className="div-24">Continue with Facebook</div>
        </div>
      </div>
      <style jsx>{`
        .div {
          border-radius: 12px;
          border: 1px solid #f2ecff;
          box-shadow: 0px 12px 24px 0px rgba(0, 72, 217, 0.05),
            0px 24px 60px 0px rgba(0, 72, 217, 0.05),
            0px 2px 4px 0px rgba(0, 72, 217, 0.1);
          background-color: #fff;
          display: flex;
          max-width: 568px;
          flex-direction: column;
          font-size: 18px;
          color: #b8bcca;
          font-weight: 400;
          padding: 40px;
        }
        @media (max-width: 991px) {
          .div {
            padding: 0 20px;
          }
        }
        .div-2 {
          display: flex;
          justify-content: space-between;
          gap: 10px;
          font-size: 24px;
          color: var(--Text-Secondary---Grey1, #586472);
          font-weight: 600;
        }
        @media (max-width: 991px) {
          .div-2 {
            max-width: 100%;
            flex-wrap: wrap;
          }
        }
        .div-3 {
          font-family: IBM Plex Sans, -apple-system, Roboto, Helvetica,
            sans-serif;
          flex-grow: 1;
        }
        @media (max-width: 991px) {
          .div-3 {
            max-width: 100%;
          }
        }
        .img {
          aspect-ratio: 1;
          object-fit: auto;
          object-position: center;
          width: 32px;
        }
        .div-4 {
          font-family: IBM Plex Sans, -apple-system, Roboto, Helvetica,
            sans-serif;
          letter-spacing: -0.2px;
          margin-top: 12px;
        }
        @media (max-width: 991px) {
          .div-4 {
            max-width: 100%;
          }
        }
        .div-5 {
          color: #6f7482;
          margin-top: 20px;
          font: 500 16px/150% IBM Plex Sans, -apple-system, Roboto, Helvetica,
            sans-serif;
        }
        @media (max-width: 991px) {
          .div-5 {
            max-width: 100%;
          }
        }
        .div-6 {
          border-radius: 4px;
          background-color: #f8fafc;
          justify-content: center;
          white-space: nowrap;
          letter-spacing: 0.16px;
          padding: 12px;
          font: 16px/150% IBM Plex Sans, -apple-system, Roboto, Helvetica,
            sans-serif;
        }
        @media (max-width: 991px) {
          .div-6 {
            max-width: 100%;
            white-space: initial;
          }
        }
        .div-7 {
          color: #6f7482;
          margin-top: 12px;
          font: 500 16px/150% IBM Plex Sans, -apple-system, Roboto, Helvetica,
            sans-serif;
        }
        @media (max-width: 991px) {
          .div-7 {
            max-width: 100%;
          }
        }
        .div-8 {
          justify-content: space-between;
          border-radius: 4px;
          background-color: #f8fafc;
          display: flex;
          gap: 20px;
          font-size: 16px;
          white-space: nowrap;
          letter-spacing: 0.16px;
          line-height: 150%;
          padding: 12px;
        }
        @media (max-width: 991px) {
          .div-8 {
            max-width: 100%;
            flex-wrap: wrap;
            white-space: initial;
          }
        }
        .div-9 {
          align-self: start;
          font-family: IBM Plex Sans, -apple-system, Roboto, Helvetica,
            sans-serif;
          margin-top: 8px;
        }
        .img-2 {
          aspect-ratio: 1;
          object-fit: auto;
          object-position: center;
          width: 24px;
        }
        .div-10 {
          display: flex;
          margin-top: 12px;
          justify-content: space-between;
          gap: 8px;
          font-size: 14px;
          color: var(--Text-Link, #0048d9);
          line-height: 140%;
        }
        @media (max-width: 991px) {
          .div-10 {
            max-width: 100%;
            flex-wrap: wrap;
          }
        }
        .img-3 {
          aspect-ratio: 1;
          object-fit: auto;
          object-position: center;
          width: 24px;
        }
        .div-11 {
          font-family: IBM Plex Sans, -apple-system, Roboto, Helvetica,
            sans-serif;
          flex-grow: 1;
          flex-basis: auto;
          margin: auto 0;
        }
        @media (max-width: 991px) {
          .div-11 {
            max-width: 100%;
          }
        }
        .div-12 {
          display: flex;
          margin-top: 4px;
          justify-content: space-between;
          gap: 8px;
          font-size: 14px;
          line-height: 140%;
        }
        @media (max-width: 991px) {
          .div-12 {
            max-width: 100%;
            flex-wrap: wrap;
          }
        }
        .img-4 {
          aspect-ratio: 1;
          object-fit: auto;
          object-position: center;
          width: 24px;
        }
        .div-13 {
          font-family: IBM Plex Sans, -apple-system, Roboto, Helvetica,
            sans-serif;
          flex-grow: 1;
          flex-basis: auto;
          margin: auto 0;
        }
        @media (max-width: 991px) {
          .div-13 {
            max-width: 100%;
          }
        }
        .div-14 {
          font-family: IBM Plex Sans, -apple-system, Roboto, Helvetica,
            sans-serif;
          justify-content: center;
          align-items: center;
          border-radius: 6px;
          background-color: var(--Text-Link, #0048d9);
          margin-top: 12px;
          color: var(--Text-Primary---White, #fff);
          font-weight: 500;
          white-space: nowrap;
          text-align: center;
          padding: 12px 60px;
        }
        @media (max-width: 991px) {
          .div-14 {
            white-space: initial;
            max-width: 100%;
            padding: 0 20px;
          }
        }
        .div-15 {
          justify-content: center;
          align-items: center;
          display: flex;
          margin-top: 20px;
          gap: 10px;
          color: #6f7482;
          white-space: nowrap;
          padding: 10px;
        }
        @media (max-width: 991px) {
          .div-15 {
            max-width: 100%;
            flex-wrap: wrap;
            white-space: initial;
          }
        }
        .div-16 {
          background-color: #b8bcca;
          align-self: stretch;
          width: 216px;
          height: 1px;
          margin: auto 0;
        }
        .div-17 {
          font-family: IBM Plex Sans, -apple-system, Roboto, Helvetica,
            sans-serif;
          align-self: stretch;
        }
        .div-18 {
          background-color: #b8bcca;
          align-self: stretch;
          width: 215px;
          height: 1px;
          margin: auto 0;
        }
        .div-19 {
          border-radius: 4px;
          border: 1px solid var(--Text-Link, #0048d9);
          display: flex;
          margin-top: 12px;
          justify-content: space-between;
          gap: 4px;
          color: var(--Text-Link, #0048d9);
          text-align: center;
          padding: 13px 20px;
        }
        @media (max-width: 991px) {
          .div-19 {
            max-width: 100%;
            flex-wrap: wrap;
          }
        }
        .img-5 {
          aspect-ratio: 1;
          object-fit: auto;
          object-position: center;
          width: 18px;
          margin: auto 0;
        }
        .div-20 {
          font-family: IBM Plex Sans, -apple-system, Roboto, Helvetica,
            sans-serif;
          flex-grow: 1;
        }
        @media (max-width: 991px) {
          .div-20 {
            max-width: 100%;
          }
        }
        .div-21 {
          border-radius: 4px;
          border: 1px solid var(--Text-Link, #0048d9);
          display: flex;
          margin-top: 12px;
          justify-content: space-between;
          gap: 4px;
          color: var(--Text-Link, #0048d9);
          text-align: center;
          padding: 13px 20px;
        }
        @media (max-width: 991px) {
          .div-21 {
            max-width: 100%;
            flex-wrap: wrap;
          }
        }
        .img-6 {
          aspect-ratio: 1;
          object-fit: auto;
          object-position: center;
          width: 18px;
          margin: auto 0;
        }
        .div-22 {
          font-family: IBM Plex Sans, -apple-system, Roboto, Helvetica,
            sans-serif;
          flex-grow: 1;
        }
        @media (max-width: 991px) {
          .div-22 {
            max-width: 100%;
          }
        }
        .div-23 {
          border-radius: 4px;
          border: 1px solid var(--Text-Link, #0048d9);
          display: flex;
          margin-top: 12px;
          justify-content: space-between;
          gap: 4px;
          color: var(--Text-Link, #0048d9);
          text-align: center;
          padding: 13px 20px;
        }
        @media (max-width: 991px) {
          .div-23 {
            max-width: 100%;
            flex-wrap: wrap;
          }
        }
        .img-7 {
          aspect-ratio: 1;
          object-fit: auto;
          object-position: center;
          width: 18px;
          margin: auto 0;
        }
        .div-24 {
          font-family: IBM Plex Sans, -apple-system, Roboto, Helvetica,
            sans-serif;
          flex-grow: 1;
        }
        @media (max-width: 991px) {
          .div-24 {
            max-width: 100%;
          }
        }
      `}</style>
    </>
  );
}
